# Generated by Django 2.1 on 2018-08-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
