# Generated by Django 2.1 on 2018-08-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_auto_20180820_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camp',
            old_name='title',
            new_name='event',
        ),
    ]
