# Generated by Django 2.1 on 2018-08-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0003_auto_20180820_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='event',
        ),
        migrations.AddField(
            model_name='camp',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
